### ISSUE TITLE
Proposal: Ansible Network Validated Content Base Application

### ISSUE THREAD

**Issue by rohitthakur2590** [ansible-collections/ansible.network#32]
# Proposal: <proposal name>
network.base application acts as core for other validated content, as it provides the platform agnostic role called  Resource Manager.This role provides a single platform-agnostics entry point to manage all the resources supported for a given network OS.
*Author*: Rohit Thakur (@rohitthakur2590)

*Date*: 2022/06/21

- Status: New
- Proposal type:  Validated Content
- Targeted Release: 
- Associated PR:  https://github.com/ansible-network/network.base
- Estimated time to implement: 4 weeks

## Motivation
Describe the reasons for this proposal.
Provide Network Base Vaidated Content to act as core for other validated content to acheive platform agnostic resource management.

### Problems
*  **Build Brownfield Inventory:** Users want to be able to get the facts for a given resource and store it as host_vars thus enabling the capability to get facts for all the hosts within the inventory and store facts in a structured format which acts as SOT. 
* **Supported Resource Query:** Users want to be able to get the list of resource modules supported for a given network os.
* **Gather:** Users want to be able to gather the facts for specified network resources.
* **Persist:** Users want to be able to gather the facts for specified network resources and persist those facts into inventory files as host vars.
* **Deploy:** Users want to be able to deploy the confguration persisted in terms of host vars on to the appliance.
* **Configure:** Users want to be able to apply configuration in a normalized manner the way resource module does.

## Solution proposal
* `resource_manager` :
This platform agnostic role enables the user to create a runtime brownfield inventory with all the configuration in terms of host vars. These host vars are  ansible facts which have been gathered through the network resource module.The tasks offered by this role could be observed as below:
Options:

#### list.yaml:
```
---
- hosts: ios
  tasks:
  - name: invoke list function
    include_role:
      name: resource_manager
    vars:
      ansible_network_os: cisco.ios.ios
      action: list
```

#### gather.yaml:
```
---
- hosts: ios
  gather_facts: false
  tasks:
  - name: invoke gather function
    include_role:
      name: resource_manager
    vars:
      action: gather
      ansible_network_os: cisco.ios.ios
      resources:
        - 'interfaces'
        - 'l2_interfaces'
        - 'l3_interfaces'
```

#### persist.yaml:
```
---
- hosts: ios
  tasks:
  - name: invoke persist function
    include_role:
      name: resource_manager
    vars:
      action: persist
      ansible_network_os: cisco.ios.ios
      resources:
        - 'interfaces'
        - 'l2_interfaces'
        - 'l3_interfaces'
```

#### deploy.yaml:
```
---
- hosts: ios
  tasks:
  - name: invoke persist function
    include_role:
      name: resource_manager
    vars:
      action: deploy
      ansible_network_os: cisco.ios.ios
      resources:
        - 'all'
```
#### config.yaml:
```
---
- hosts: ios
  tasks:
  - name: invoke persist function
    include_role:
      name: resource_manager
    vars:
      action: configure
      ansible_network_os: cisco.ios.ios
      config:
        - name: "GigabitEthernet0/0"
          description: "Edited with Configure operation"
      state: merged
```

## Testing (optional)
* Add integration and unit test for `resource_manager` tasks. 
* Add integration and unit test for `param_list_compare` filter plugin. 

## Documentation (optional)
* Update module documentation for `betwork.base` and `resource_manager`
