### ISSUE TITLE
Proposal: Ansible Network Validated Content BGP Application

### ISSUE THREAD

**Issue by rohitthakur2590** [ansible-collections/ansible.network#33]
# Proposal: <proposal name>
- Validated content network.bgp enables the users to perform supported health_checks on bgp establishment.
- Enables the user to manage the BGP resources independent of platforms, so users can manage and configure BGP routes with operations like gather, deploy and persist, config.
 
*Author*: Rohit Thakur (@rohitthakur2590)

*Date*: 2022/06/21

- Status: New
- Proposal type:  Validated Content
- Targeted Release: 
- Associated PR: https://github.com/ansible-network/network.bgp/pull/1
- Estimated time to implement: 4 weeks

## Motivation
Describe the reasons for this proposal.
Provide Network BGP Vaidated Content to perform BGP health checks and manage BGP resources.

### Problems
*  **Build Brownfield Inventory:** Users want to be able to get the facts for BGP resources and store it as host_vars thus enabling the capability to get facts for all the hosts within the inventory and store facts in a structured format which acts as SOT. 
* **BGP Resource Management:**  Users want to be able to manage the BGP global and BGP address family configurations.This also includes the enablement of gathering facts, updating BGP resource host-vars and deploying config onto the appliance.
* **BGP Health Checks::**  Users want to be able to perform health checks for BGP applications.These health checks should be able to provide the BGP neighborship status with  necessary details.

## Solution proposal
* `ansible.bgp.run` :
- This platform agnostic role enables the user to perform BGP health checks.Users can perfrom following health checks:
    - all_neigbors_up
    - all_neighbors_down
    - min_neighbors_up
-  This role enables users to create a runtime brownfield inventory with all the BGP configuration in terms of host vars. These host vars are  ansible facts which have been gathered through the `*_bgp_global` and `*_bgp_address_family` network resource module.The tasks offered by this role could be observed as below:
Options:

#### health_checks.yaml:
```
---
- hosts: junos
  tasks:
  - name: BGP Manager
    include_role:
      name: ansible.bgp.run
    vars:
      actions:
        - name: health_check
          vars:
            details: True
            checks:
              - name: all_neighbors_up
              - name: all_neighbors_down
              - name: min_neighbors_up
                min_count: 
```

#### bgp_persist.yaml:
```
---
- hosts: junos
  tasks:
  - name: BGP Manager
    include_role:
      name: ansible.bgp.run
    vars:
      actions:
        - name: persist
```

#### bgp_persist.yaml:
```
---
- hosts: junos
  tasks:
  - name: BGP Manager
    include_role:
      name: ansible.bgp.run
    vars:
      actions:
        - name: gather
```

#### bgp_persist.yaml:
```
---
- hosts: junos
  tasks:
  - name: BGP Manager
    include_role:
      name: ansible.bgp.run
    vars:
      actions:
        - name: deploy
```
