### ISSUE TITLE
Socket is closed error

### ISSUE THREAD

**Issue by ashish-k-panigrahy** [ansible-collections/ansible.network#36]
I have been seeing this issue with `nxos_config` module. I don't know what the cause is and how to solve it.

use case/example:
```

- name: Delete IP block 
  nxos_config:
    lines: "no ip prefix-list PLIST-XX1"
    save_when: always
  register: ip_delete_result
  until: ip_delete_result is succeeded
  retries: 3
```

Error:
`fatal: [clf01-r03]: FAILED! => {"attempts": 3, "changed": false, "msg": "Socket is closed"}`

_Originally posted by @ashish-k-panigrahy in https://github.com/ansible-collections/ansible.netcommon/issues/202#issuecomment-1812426396_
